apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: "http://host.docker.internal:9090" # ⚡ FIXED: Quotes remove VS Code warnings
    isDefault: true
    uid: "PROMETHEUS_PROD_ENGINE"
    editable: true
    version: 4
    jsonData:
      httpMethod: POST
