apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.17.0.1:9090 #  FIXED: Points to the Docker host gateway where Prometheus listens
    isDefault: true
    uid: "PROMETHEUS_PROD_ENGINE" # FIXED: Explicit ID for your dashboard mapping
    editable: true
